### ISSUE TITLE
[1.19.2] Server Crash: Ticking Entity

### ISSUE THREAD

**Issue by Darkfiend009** [KitKait2001/roamers#1]
I was hanging out with one of the roamers watching them mine and the server crashed.

Minecraft: 1.19.2
Roamers:  v1.2
Forge: 43.2.0

Crash Report: https://pastebin.com/n2aWtLHW

**Comment by KitKait2001** [comment]
Hello! This is definitely on my end, sorry for that! Thank you for the crash report! This was very helpful!

**Comment by KitKait2001** [comment]
I fixed it now, and will be updated on version 1.3!

**Comment by Darkfiend009** [comment]
My pleasure! I am really enjoying this mod. I find myself watching them for an hour or 2 at times just to see what they will do next. Roamers may be better at vanilla minecraft than most of my friends haha

I am currently modifying a player's playerdata location by hand back to their spawn point so that the server doesn't keep crashing.

There is always a work around!
