### ISSUE TITLE
GAME IS CRUSHING

### ISSUE THREAD

**Issue by BugrahanTelli** [KitKait2001/roamers#11]
[crash-2024-10-17_10.57.23-client.txt](https://github.com/user-attachments/files/17408373/crash-2024-10-17_10.57.23-client.txt)

When Im playing survival there is no roamers spawning and sometimes the game suddenly crush (I think it is trying to spawn roamers) and I wanted to try that in the creative world to spawn some roamers with the egg. the game crashed again. Can you look at it ?

**Comment by KitKait2001** [comment]
This seems to be an optifine crash that the roamer triggered. Let me take a look at it and I'll get back to you. :)

**Comment by BugrahanTelli** [comment]
Thank you so much, happy to help.

**Comment by KitKait2001** [comment]
Thanks! Do you mind sending the modpack that you are using (if you are using CurseForge)?

**Comment by BugrahanTelli** [comment]
[mods_part1.zip](https://github.com/user-attachments/files/17413389/mods_part1.zip)
[mods_part2.zip](https://github.com/user-attachments/files/17413394/mods_part2.zip)

here they are. I use all of them it was a big folder so I needed to separate it.

**Comment by KitKait2001** [comment]
Thank you! Feel free to add me on Discord if you have the app. If you don't have it no worries!
https://discordapp.com/users/1012124539242684527
My user profile link to send DMs in case you need it :)

**Comment by BugrahanTelli** [comment]
I wish but it got cancelled where I live soooo, If I need anything I'll just comment on the roamers page. Thank you for your work.

**Comment by KitKait2001** [comment]
Youre totally fine! Sorry discord got cancelled jeez! :/

Also thanks a lot! I installed your exact mods and it is running fine so I think it might be a setting? Can you copy the config folder and the "optionsof.txt" file? This will be the last time I'll ask you to upload some things lol sorry! 
Just trying to troubleshoot so you can play the game lol!

**Comment by BugrahanTelli** [comment]
[config.zip](https://github.com/user-attachments/files/17413980/config.zip)
[optionsof.txt](https://github.com/user-attachments/files/17413986/optionsof.txt)
And there is "exit code : -1"  (If it helps)
It is totally fine. I just want to play with roamers mod It got me so excited. I'll do whatever it takes.
Can resourcepacks cause this? I can send them too.

**Comment by KitKait2001** [comment]
Yeah thanks lol xD It might be resource packs as well definetly!!

**Comment by BugrahanTelli** [comment]
[colourful containers darkmode.zip](https://github.com/user-attachments/files/17414191/colourful.containers.darkmode.zip)
[FA+All_Extensions-v1.4.zip](https://github.com/user-attachments/files/17414193/FA%2BAll_Extensions-v1.4.zip)
[Fancy Crops v1.0 f5-34.zip](https://github.com/user-attachments/files/17414194/Fancy.Crops.v1.0.f5-34.zip)
[FreshAnimations_v1.9.2.zip](https://github.com/user-attachments/files/17414197/FreshAnimations_v1.9.2.zip)
[freshly-modded-1-5-7.zip](https://github.com/user-attachments/files/17414198/freshly-modded-1-5-7.zip)
[mobs-refreshed-fa-v2.1.zip](https://github.com/user-attachments/files/17414199/mobs-refreshed-fa-v2.1.zip)
[VanillaTweaks_r641539_MC1.21.x.zip](https://github.com/user-attachments/files/17414200/VanillaTweaks_r641539_MC1.21.x.zip)
[Visible Ores2.12.zip](https://github.com/user-attachments/files/17414201/Visible.Ores2.12.zip)
I hope this helps.

**Comment by KitKait2001** [comment]
Hi! I found an issue with optifine and the shaders you used. I saw your shaders in the crash log lol. I turned them on and the roamers did not render properly. Must be a compatibility issue between either mods/resourcepacks, optifine, and shaders. 

![2024-10-17_11 07 40](https://github.com/user-attachments/assets/4bb5875f-d3de-4014-a373-02ca7992516a)

This is my screen in the game, and the roamer's base skin is invisible. Your settings might have made it crash for you.

Try without optifine and see if this helps. 

There is also an alternative to optifine: Sodium + Iris. Also, to have Fresh Animations work, I would download EMF (Entity Model Features) and ETF (Entity Texture Features). These mods will make sure that the shaders and animations work. 

(Also try Fresh Moves Resource Pack to animate the roamers if ya want to! :D)
https://www.curseforge.com/minecraft/texture-packs/fresh-moves

Hopefully this helps!!

**Comment by BugrahanTelli** [comment]
TYSM. I'll look at them right away.  Thank you for your time <3

**Comment by KitKait2001** [comment]
Actually nvm these are only for NeoForge sorry lol! Try optifine and play with the settings/resourcepacks a bit to see which ones will work. Hope this helps, and thanks for troubleshooting with me! :)

**Comment by BugrahanTelli** [comment]
Dont mention it. Love your effort. I'll try and I think I will bother you a lot  :)

**Comment by BugrahanTelli** [comment]
I just deleted all my mods my resourcepacks, shaders even the optifine but roamers and I just run the game but still same issue occurs. Sorry for bothering nonstop.

**Comment by KitKait2001** [comment]
You're fine. That is really weird. Ill take a closer look and see whats happening. :)

**Comment by KitKait2001** [comment]
Okay, after looking over your crash log, I saw your locale could be the issue with parsing the resource locations in my mod. I uploaded an unreleased version of roamers on my Google Drive. :)

[Link to File](https://drive.google.com/file/d/10PSzBdBHl0ou5XKD3Scj8YxG18DTWapX)

If you can download it and test the patch on your computer that would be huge. Just to see if it works lol I have no way to test it on my end :)

**Comment by BugrahanTelli** [comment]
You are AWESOME. It is working now with all my mods. However, with optifine the loading crushes but it is totaly fine. I cant thank you enough. I REALLY thank you for your time. I hope you achieve everything that you want. <3
