### ISSUE TITLE
[Suggestion] Just Expressions or Fresh Animation Version

### ISSUE THREAD

**Issue by Beez3-A** [KitKait2001/roamers#8]
Hello KitKait

I can see alot of time and effort you spent on this wonderful mod

with minecraft evolving especially with Fresh Animations these days,  would be a great Idea to make this mod animated. 

It's actually really easy as you already have the textures all it just needs it to be adjusted to work with animations 

I

**Comment by KitKait2001** [comment]
Hello! Thanks for the suggestion! :D Implemented in version 2.1 for 1.21.1 <3

**Comment by Beez3-A** [comment]
Impressive 

you updated it so fast 👍

**Comment by KitKait2001** [comment]
Yeah xD was just a last-minute addition since I just added a few pixels lol! It really looks great tho! The npcs use the player model so Fresh Moves works for them! :)

**Comment by Beez3-A** [comment]
Yeah looks really really cool actually
